### PR TITLE
Initiating release of 0.11.1

### PR DESCRIPTION
**Pull request by dfarrell07**
Initiating release of 0.11.1

### CODE REVIEW

**Review by skitt — APPROVED** [review]

**Review by nyechiel — APPROVED** [review]

**Comment by skitt** [comment]
Aargh, E2E is failing again because the release doesn’t exist yet... @mkolesnik I thought that was fixed, or is it only on `devel`?

**Comment by skitt** [comment]
> Aargh, E2E is failing again because the release doesn’t exist yet... @mkolesnik I thought that was fixed, or is it only on `devel`?

And that’s a silly question because there isn’t that distinction in the release project.

**Review by mkolesnik — APPROVED** [review]
The E2E fails properly because the operator image build failed so the image wasn't published to Quay.

Failed job: https://github.com/submariner-io/submariner-operator/runs/4724291047?check_suite_focus=true

Specifically it's something to do with the bundle:
```
  #8 1.232 time="2022-01-06T07:23:46Z" level=fatal msg="permissive mode disabled" error="error loading manifests from directory: error loading package into db: Invalid bundle submariner.v0.11.0, replaces nonexistent bundle submariner.v0.12.0"
```

**Comment by dfarrell07** [comment]
So do we merge this over that bundle failure?

**Comment by dfarrell07** [comment]
Also note https://github.com/submariner-io/submariner-operator/pull/1739.

**Comment by mkolesnik** [comment]
> So do we merge this over that bundle failure?

No the image needs to exist or the actual release will fail as well

**Comment by skitt** [comment]
https://github.com/submariner-io/submariner-operator/pull/1744 will allow the operator bundle image to be built.

**Comment by dfarrell07** [comment]
It looks like the tests that were failing before are going to pass this time :partying_face:. Thanks @skitt and @mkolesnik!

**Pull request merged**
