### PR TITLE
Make sure to sync to upstream before changes

### PR DESCRIPTION
**Pull request by mkolesnik**
Since the merged commit will have a different hash, we need to make sure
to sync up the local branch before doing any additional changes.

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

### CODE REVIEW

**Review by skitt — APPROVED** [review]

**Review by tpantelis — APPROVED** [review]

**Comment by tpantelis** [comment]
The **Linting/Shell** check failed but it's not required... it seems it should be. There's other jobs that aren't required as well.

**Comment by tpantelis** [comment]
> The **Linting/Shell** check failed but it's not required... it seems it should be. There's other jobs that aren't required as well.

I made other jobs required.

**Comment by mkolesnik** [comment]
> The **Linting/Shell** check failed but it's not required... it seems it should be. There's other jobs that aren't required as well.

Yes I fixed the bogus failure SC2153 and the general failure should be fixed

**Comment by dfarrell07** [comment]
This seems to be causing an issue with https://github.com/submariner-io/releases/pull/280, see: https://kubernetes.slack.com/archives/C010RJV694M/p1639077817371400?thread_ts=1639068146.370500&cid=C010RJV694M

**Comment by skitt** [comment]
> This seems to be causing an issue with #280, see: https://kubernetes.slack.com/archives/C010RJV694M/p1639077817371400?thread_ts=1639068146.370500&cid=C010RJV694M

No, the failure there isn’t related to this (see my comment there).

**Pull request merged**
