### PR TITLE
Start 0.10.0-m2 branching phase

### PR DESCRIPTION
**Pull request by dfarrell07**
Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

### CODE REVIEW

**Comment by dfarrell07** [comment]
Related docs clarification: https://github.com/submariner-io/submariner-website/pull/533

**Comment by dfarrell07** [comment]
Do I have this right with the branch being optional, @mkolesnik?

**Review by skitt — APPROVED** [review]

**Comment by dfarrell07** [comment]
Nevermind, we don't do this phase for non-stable releases. :sweat_smile:

**Review by nyechiel — CHANGES_REQUESTED** [review]
https://submariner.io/development/release-process/#step-0-create-a-stable-branch-if-necessary makes it clear that this is needed for stable releases only (milestone releases are internal dev releases, and there is intention to maintain them). You can skip it and start from the Shipyard phase

**Comment by dfarrell07** [comment]
New clarification: https://github.com/submariner-io/submariner-website/pull/534

**Pull request closed without merging**
