### PR TITLE
Advancing 0.15.0 release to status: projects

### PR DESCRIPTION
**Pull request by dfarrell07**

### CODE REVIEW

**Comment by dfarrell07** [comment]
```
[15:59:14.485] [dir=releases; fn=dryrun]$ docker pull quay.io/submariner/submariner-gateway:release-0.15-a7276fcf70b5
Error response from daemon: manifest for quay.io/submariner/submariner-gateway:release-0.15-a7276fcf70b5 not found: manifest unknown: manifest unknown
```

[E2E](https://github.com/submariner-io/releases/actions/runs/4863237160/jobs/8670666973?pr=708#logs)

**Comment by dfarrell07** [comment]
Failing in both E2E and again after a re-run. I don't see the SHA in question on Quay.

https://quay.io/repository/submariner/submariner-gateway?tab=tags&tag=latest

**Comment by dfarrell07** [comment]
Oh wow, this job is still running 37min later :exploding_head: 

https://github.com/submariner-io/submariner/actions/runs/4862952908

**Review by tpantelis — APPROVED** [review]

**Comment by sridhargaddam** [comment]
> Oh wow, this job is still running 37min later exploding_head
> 
> https://github.com/submariner-io/submariner/actions/runs/4862952908

It succeeded just now :)

**Review by nyechiel — APPROVED** [review]

**Review by sridhargaddam — APPROVED** [review]

**Review by skitt — APPROVED** [review]

**Pull request merged**
