### PR TITLE
Start 0.10.0-m2.1 shipyard release phase

### PR DESCRIPTION
**Pull request by dfarrell07**
Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

### CODE REVIEW

**Review by tpantelis — APPROVED** [review]

**Comment by dfarrell07** [comment]
I'm not sure if we need this or if we can fix m2. See: https://kubernetes.slack.com/archives/C010RJV694M/p1623693057066400

**Review by mkolesnik — CHANGES_REQUESTED** [review]
no need for this, shipyard docker image tag for the release is only needed when it's on a stable branch

**Comment by mangelajo** [comment]
Yeah, this would be only for the go code in a pre-release. The dapper image reference is not modified for pre-releases.

**Comment by dfarrell07** [comment]
Not required, continuing with m2 here: https://github.com/submariner-io/releases/pull/161

**Pull request closed without merging**
