### PR TITLE
Update krew-index on release tag

### LINKED ISSUE #904: Krew updates fail on release branches
See https://github.com/submariner-io/releases/actions/runs/7652504611/job/20852404956:

```
Run rajatjindal/krew-release-bot@v0.0.46
  with:
/usr/bin/docker run --name ghcriorajatjindalkrewreleasebotv0046_21faec --label e4beb7 --workdir /github/workspace --rm -e "INPUT_WORKDIR" -e "INPUT_KREW_TEMPLATE_FILE" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/releases/releases":"/github/workspace" ghcr.io/rajatjindal/krew-release-bot:v0.0.46
time="2024-01-25T09:52:24Z" level=fatal msg="GITHUB_REF expected to be of format refs/tags/<tag> but found \"refs/heads/release-0.17\""
```

### PR DESCRIPTION
**Pull request by tpantelis**
Fixes https://github.com/submariner-io/releases/issues/904

### CODE REVIEW

**Comment by tpantelis** [comment]
I'm not sure if there's a way to actually test the new GHA now but, once merged, we should be able to manually trigger it from the **Actions** tab for the 0.16.3 release tag.

**Review by vthapar — APPROVED** [review]

**Comment by skitt** [comment]
> I'm not sure if there's a way to actually test the new GHA now but, once merged, we should be able to manually trigger it from the **Actions** tab for the 0.16.3 release tag.

See [the GHA docs](https://github.com/rajatjindal/krew-release-bot?tab=readme-ov-file#testing-the-template-file):

```
podman run -v .krew.yaml:/tmp/template-file.yaml ghcr.io/rajatjindal/krew-release-bot:v0.0.46 \
krew-release-bot template --tag v0.17.0-rc0 --template-file /tmp/template-file.yaml
```

in the releases project (for v0.17.0-rc0). This produces the index which would be pushed to update [the `subm.yaml` file in the Krew index](https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/subm.yaml).

**Review by skitt — CHANGES_REQUESTED** [review]
This would fix the job, but there’s a more general problem I think we need to address before we get things working on all releases: since we can only publish one version of the `subm` plugin, we need to ensure that (a) we only publish actual releases (not rcs etc.) and (b) we only publish the latest release on the latest branch.

**Comment by tpantelis** [comment]
> This would fix the job, but there’s a more general problem I think we need to address before we get things working on all releases: since we can only publish one version of the `subm` plugin, we need to ensure that (a) we only publish actual releases (not rcs etc.) 

The [krew-release-bot](https://github.com/rajatjindal/krew-release-bot?tab=readme-ov-file) takes care of that: "_If a release is marked as a 'prerelease' in github, it will not be released to the krew index."_.

> and (b) we only publish the latest release on the latest branch.

I was thinking about that too. I'm not sure how we can do that....

**Comment by tpantelis** [comment]
> > I'm not sure if there's a way to actually test the new GHA now but, once merged, we should be able to manually trigger it from the **Actions** tab for the 0.16.3 release tag.
> 
> See [the GHA docs](https://github.com/rajatjindal/krew-release-bot?tab=readme-ov-file#testing-the-template-file):
> 
> ```
> podman run -v .krew.yaml:/tmp/template-file.yaml ghcr.io/rajatjindal/krew-release-bot:v0.0.46 \
> krew-release-bot template --tag v0.17.0-rc0 --template-file /tmp/template-file.yaml
> ```
> 
> in the releases project (for v0.17.0-rc0). This produces the index which would be pushed to update [the `subm.yaml` file in the Krew index](https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/subm.yaml).

yeah that will test the _.krew.yaml_ file but not the GHA.

**Comment by skitt** [comment]
> The [krew-release-bot](https://github.com/rajatjindal/krew-release-bot?tab=readme-ov-file) takes care of that: "_If a release is marked as a 'prerelease' in github, it will not be released to the krew index."_.

Ah yes, and we mark them correctly already.

**Comment by tpantelis** [comment]
I found a way to get the release tag marked as the latest.

**Review by skitt — APPROVED** [review]

**Pull request merged**
